@startuml nomor1
start
:Tampilan Menu;
while (true)
    :Meminta pengguna memilih minuman (Teh/Kopi);
    if (pilihan == "teh") then (Teh)
        :Tampilkan menu Teh;
        break
    elseif (pilihan == "kopi") then (Kopi)
        :Tampilkan menu Kopi;
        break
    else (Pilihan tidak valid)
        :Tampilkan "Pilihan tidak valid. Silakan pilih antara 'Teh' atau 'Kopi';";
    endif
endwhile

while (true)
    :Input pilihan nomor menu atau 0 untuk selesai;
    if (Pilihan nomor = 0) then (yes)
        :Keluar loop;
    else (no)
        if (Nomor valid) then (yes)
            :Input jumlah item yang diinginkan;
            :Hitung dan tambahkan ke total harga;
        else (no)
            :Tampilkan pesan "Pilihan tidak valid";
        endif
    endif
endwhile
:selesai;
@enduml
